
# Usage:
# docker-compose build --build-arg r5version=$(cat build/version.txt)
# docker-compose up

version: '3'
services:

  r5:
    container_name: r5-backend
    build: .
    depends_on:
      - mongo
    links:
      - mongo
#    deploy:
#      resources:
#        limits:
#          cpus: '55'
    ports:
      - "7070:7070"
    environment:
      - DATABASE_URI=mongodb://mongo:27017/analysis
    volumes:
      - r5-cache:/usr/data/cache  # cache 디렉토리를 볼륨에 마운트


  ui:
    container_name: r5-ui
    depends_on:
      - mongo
    image: r5-ui
    ports:
      - "3000:3000"
    links:
      - r5
      - mongo
    environment:
      - MONGODB_URL=mongodb://mongo:27017/analysis
#    volumes:
#      - ./ui-env:/ui/.env.local:ro

  mongo:
    container_name: mongo
    image: mongo
    restart: always
    volumes:
      - mongo-volume:/data/db:rw
    ports:
      - "27017:27017"

volumes:
  mongo-volume:
  r5-cache:      # 볼륨을 여기서 정의