name: 'Cypress Integration Tests'

on: [push]

jobs:
  cypressIntegration:
    services:
      mongo:
        image: mongo
        ports:
          - 27017:27017

    runs-on: ubuntu-latest
    steps:
      # Checkout each repo into sub-directories
      - uses: actions/checkout@v2
        with:
          repository: conveyal/analysis-ui
          ref: a869cd11919343a163e110e812b5d27f3a4ad4c8
          path: ui
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          path: r5
      # Build .jar and copy to ./ui directory (along with config file)
      # Cache Gradle dependencies to speed up the shadow jar build
      - uses: actions/cache@v1
        id: cache
        with:
          path: ~/.gradle/caches
          key: gradle-caches
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - run: gradle shadowJar -x test
        working-directory: r5
      - run: cp $(ls ./r5/build/libs/*-all.jar | head -n1) ./ui/latest.jar
      - run: cp ./r5/analysis.properties.template ./ui/analysis.properties

      # Install / cache dependencies with Cypress to handle caching Cypress binary.
      - uses: actions/setup-node@v2
        with:
          node-version: '12'        
      - uses: cypress-io/github-action@v2
        env:
          NEXT_PUBLIC_BASEMAP_DISABLED: true
          NEXT_PUBLIC_CYPRESS: true
          NEXT_PUBLIC_MAPBOX_ACCESS_TOKEN: ${{ secrets.MAPBOX_ACCESS_TOKEN }}
        with:
          build: yarn build
          start: yarn start, yarn start-backend # runs frontend and java server together
          wait-on: 'http://localhost:3000, http://localhost:7070/version'
          wait-on-timeout: 60
          working-directory: ui
